import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
//import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });
//const SpaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub user Searcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className=""
      >
      <body className={robotoMono.className}>
        <div className=" grid min-h-screen max-w-500 place-content-center bg-blue-50 px-4 dark:bg-[#151E35] ">
          <div className="grid sm:w-[500px] md:w-[600px] l:w-[700px]">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
